[project]
name = "library-management-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyfiglet>=1.0.3",
    "tabulate>=0.9.0",
]
